class ThreadModel {
  final String threadId;
  final String firstMessage;
  final String firstSenderId;
  final DateTime startedAt;
  final int messageCount;
  final DateTime? lastMessageAt;
  final String? summary; // AI-generated by Groq
 
  ThreadModel({
    required this.threadId,
    required this.firstMessage,
    required this.firstSenderId,
    required this.startedAt,
    this.messageCount = 1,
    this.lastMessageAt,
    this.summary,
  });
 
  ThreadModel copyWith({
    int? messageCount,
    DateTime? lastMessageAt,
    String? summary,
  }) => ThreadModel(
    threadId: threadId,
    firstMessage: firstMessage,
    firstSenderId: firstSenderId,
    startedAt: startedAt,
    messageCount: messageCount ?? this.messageCount,
    lastMessageAt: lastMessageAt ?? this.lastMessageAt,
    summary: summary ?? this.summary,
  );
}