// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh5qF1mHSFEfVj0SOlRwlyIPafKLH4X0k',
    appId: '1:179421442602:web:d889ce49d3209fe4314953',
    messagingSenderId: '179421442602',
    projectId: 'threadflow-f2ef7',
    authDomain: 'threadflow-f2ef7.firebaseapp.com',
    storageBucket: 'threadflow-f2ef7.firebasestorage.app',
    measurementId: 'G-607YQMP3SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDySEibcGjHNB2wgcw-e2TsmBPaP9A3XsI',
    appId: '1:179421442602:android:c0a5111f896d99f8314953',
    messagingSenderId: '179421442602',
    projectId: 'threadflow-f2ef7',
    storageBucket: 'threadflow-f2ef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINvHO-mgGCSvq9BBDTUjh78Un7Nu4Ovk',
    appId: '1:179421442602:ios:84df34cddb455528314953',
    messagingSenderId: '179421442602',
    projectId: 'threadflow-f2ef7',
    storageBucket: 'threadflow-f2ef7.firebasestorage.app',
    iosBundleId: 'com.example.threadflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBINvHO-mgGCSvq9BBDTUjh78Un7Nu4Ovk',
    appId: '1:179421442602:ios:84df34cddb455528314953',
    messagingSenderId: '179421442602',
    projectId: 'threadflow-f2ef7',
    storageBucket: 'threadflow-f2ef7.firebasestorage.app',
    iosBundleId: 'com.example.threadflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh5qF1mHSFEfVj0SOlRwlyIPafKLH4X0k',
    appId: '1:179421442602:web:25663c8ea53b2a48314953',
    messagingSenderId: '179421442602',
    projectId: 'threadflow-f2ef7',
    authDomain: 'threadflow-f2ef7.firebaseapp.com',
    storageBucket: 'threadflow-f2ef7.firebasestorage.app',
    measurementId: 'G-MZ75S348XW',
  );
}
